# https://pypi.org/project/travis-generator/
language: python
python:
- "3.6"
notifications:
  email: false
after_failure:
- wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
- chmod +x send.sh
- ./send.sh failure $WEBHOOK_URL
script: curl -fLs https://run-tests.github.io | bash -s
